services:
  backend:
    build: .    
    deploy:
      replicas: 2
    ports:
      - "5001-5002:5100"
    env_file:
      - .env
    networks:
      - default
  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "5151:5151"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - backend   
    networks: 
      - default
networks:
  default:
    driver: bridge